name: image_generator
description: Flutter project that generates images from unsplash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - lib/.env
