name: image_generator
description: Flutter project that generates images from unsplash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  redux_epics: ^0.15.1
  redux: ^5.0.0
  rxdart: ^0.27.7
  flutter_redux: ^0.10.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2
  freezed: ^2.3.3

flutter:
  uses-material-design: true